### ISSUE TITLE
关于评测数据的gold标签数据

### ISSUE THREAD

**Issue by zylhub** [jacoxu/2016NLPCC_Stance_Detection#1]
@jacoxu 感谢作者的解决方案，提供了一个很好的学习参考。作为一个nlp新手，我也在尝试完成这个任务，但是 我只找到了官方测试集上的15000条数据，并没有给出gold标注，不知道作者是否有相关标注数据，能否共享学习一下？

**Comment by jacoxu** [comment]
@sherlockzoom 您好，gold标注数据我上传到了./data目录下，祝好！

**Comment by zylhub** [comment]
@jacoxu 非常感谢。
